blank_issues_enabled: true
contact_links:
  - name: GitHub Community Support
    url: https://github.com/
    about: Please ask and answer questions here.
    context:
        button-text: Get Started
  - name: GitHub Security Bug Bounty
    url: https://github.com/
    about: Please report security vulnerabilities here.
