blank_issues_enabled: false
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this report!
contact_links:
  - name: GitHub Community Support
    url: https://github.com/
    about: Please ask and answer questions here.
  - name: GitHub Security Bug Bounty
    url: https://github.com/
    about: Please report security vulnerabilities here.
